[project]
name = "ida-colors"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lark>=1.2.2",
    "pydantic>=2.11.7",
]

[dependency-groups]
dev = [
    "idapro>=0.0.4",
    "mypy>=1.16.1",
    "pytest>=8.4.2",
    "ruff>=0.14.1",
]
